CXX     = g++ -O2
CXXFLAGS =

all:
	${CXX} ${CXXFLAGS} ukqcd2mdp.cpp -o ukqcd2mdp.exe
	${CXX} ${CXXFLAGS} milc2mdp.cpp -o milc2mdp.exe
	${CXX} ${CXXFLAGS} asciimilc2mdp.cpp -o asciimilc2mdp.exe
	${CXX} ${CXXFLAGS} duncan2mdp.cpp -o duncan2mdp.exe
	${CXX} ${CXXFLAGS} luigi2mdp.cpp -o luigi2mdp.exe
