CC     = g++
CFLAGS = -DLINUX -O3 -std=c++14 -I../Libraries

all:
	${CC} ${CFLAGS} asciimilc2mdp.cpp -o asciimilc2mdp.exe
	${CC} ${CFLAGS} duncan2mdp.cpp -o duncan2mdp.exe
	${CC} ${CFLAGS} luigi2mdp.cpp -o luigi2mdp.exe
	${CC} ${CFLAGS} mdp2asciimilc.cpp -o mdp2asciimilc.exe
	${CC} ${CFLAGS} milc2mdp.cpp -o milc2mdp.exe
	${CC} ${CFLAGS} nersc2mdp.cpp -o nersc2mdp.exe
	${CC} ${CFLAGS} ukqcd2mdp.cpp -o ukqcd2mdp.exe
